name: Jakarta Contexts and Dependency Injection CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: "Build CDI - JDK ${{matrix.java.name}}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - {
            name: "11",
            java-version: 11,
          }
          - {
            name: "16",
            java-version: 16,
          }
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java.name }}
        uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ matrix.java.java-version }}
      - name: "Maven install"
        run: |
          mvn -Pstaging install -DskipTests=true -B -V
      - name: "Maven test"
        run: |
          mvn -Pstaging test -B
